title: Aparna Arun
description: Final Year Law Student | Commercial Law Enthusiast
theme: minima

author:
  name: Aparna Arun
  email: aparnaaarun1105@gmail.com

social_links:
  linkedin: 
  github: 

show_excerpts: false
markdown: kramdown
